vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        clips:
            uri_prefix: /videos/clips
            upload_destination: '%kernel.project_dir%/public/videos/clips'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
